# Configuration for https://goreleaser.com/
project_name: authenticator

builds:
  - binary: aws-iam-authenticator
    main: ./cmd/aws-iam-authenticator/
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w -X pkg.Version={{.Version}} -X pkg.CommitID={{.Commit}} -buildid=''"

dockers:
  - binaries:
     - aws-iam-authenticator
    dockerfile: Dockerfile.scratch
    image_templates:
     - "ghcr.io/kronostechnologies/aws-iam-authenticator:{{ .Tag }}"

snapshot:
  name_template: "git-{{.ShortCommit}}"

archives:
  - id: bin
    format: binary

